packages:
  - 'global/*'
  - '!packages/a11y'
  - '!packages/components'
  - '!packages/template'
  - 'packages/animation'
  - 'packages/autovideo'
  - 'packages/cmscombine'
  - 'packages/cmscore'
  - 'packages/cmscss'
  - 'packages/cmsfilter'
  - 'packages/cmsload'
  - 'packages/cmsnest'
  - 'packages/cmsprevnext'
  - 'packages/cmssave'
  - 'packages/cmsselect'
  - 'packages/cmsslider'
  - 'packages/cmssort'
  - 'packages/cmstabs'
  - 'packages/codehighlight'
  - 'packages/copyclip'
  - 'packages/countitems'
  - 'packages/displayvalues'
  - 'packages/docs'
  - 'packages/favcustom'
  - 'packages/linkblockedit'
  - 'packages/mirrorclick'
  - 'packages/mirrorinput'
  - 'packages/rangeslider'
  - 'packages/richtext'
  - 'packages/scrolldisable'
  - 'packages/selectcustom'
  - 'packages/sliderdots'
  - 'packages/smartlightbox'
  - 'packages/toc'
